create TABLE rapid__match_notes AS 
select distinct 'noonan_syndrome' as disease_alias, * from cohorts__rare_noonan_syndrome
 UNION select distinct 'williams_syndrome' as disease_alias, * from cohorts__rare_williams_syndrome
 UNION select distinct '22q11_2_deletion_syndrome' as disease_alias, * from cohorts__rare_22q11_2_deletion_syndrome
 UNION select distinct 'heterotaxy_syndrome' as disease_alias, * from cohorts__rare_heterotaxy_syndrome
 UNION select distinct 'marfan_syndrome' as disease_alias, * from cohorts__rare_marfan_syndrome
 UNION select distinct 'arterial_tortuosity_syndrome' as disease_alias, * from cohorts__rare_arterial_tortuosity_syndrome
 UNION select distinct 'alagille_syndrome' as disease_alias, * from cohorts__rare_alagille_syndrome
 UNION select distinct 'treacher_collins_syndrome' as disease_alias, * from cohorts__rare_treacher_collins_syndrome
 UNION select distinct 'moebius_syndrome' as disease_alias, * from cohorts__rare_moebius_syndrome
 UNION select distinct 'epidermolysis_bullosa' as disease_alias, * from cohorts__rare_epidermolysis_bullosa
 UNION select distinct 'medium_chain_acyl_coa_dehydrogenase_deficiency' as disease_alias, * from cohorts__rare_medium_chain_acyl_coa_dehydrogenase_deficiency
 UNION select distinct 'carbamoyl_phosphate_synthetase_i_deficiency' as disease_alias, * from cohorts__rare_carbamoyl_phosphate_synthetase_i_deficiency
 UNION select distinct 'glutaric_aciduria_type_1' as disease_alias, * from cohorts__rare_glutaric_aciduria_type_1
 UNION select distinct 'salla_disease' as disease_alias, * from cohorts__rare_salla_disease
 UNION select distinct 'wilson_disease' as disease_alias, * from cohorts__rare_wilson_disease
 UNION select distinct 'menkes_disease' as disease_alias, * from cohorts__rare_menkes_disease
 UNION select distinct 'x_linked_adrenoleukodystrophy' as disease_alias, * from cohorts__rare_x_linked_adrenoleukodystrophy
 UNION select distinct 'leigh_syndrome' as disease_alias, * from cohorts__rare_leigh_syndrome
 UNION select distinct 'pompe_disease' as disease_alias, * from cohorts__rare_pompe_disease
 UNION select distinct 'hurler_syndrome' as disease_alias, * from cohorts__rare_hurler_syndrome
 UNION select distinct 'sanfilippo_syndrome' as disease_alias, * from cohorts__rare_sanfilippo_syndrome
 UNION select distinct 'smith_lemli_opitz_syndrome' as disease_alias, * from cohorts__rare_smith_lemli_opitz_syndrome
 UNION select distinct 'cystinosis' as disease_alias, * from cohorts__rare_cystinosis
 UNION select distinct 'isolated_growth_hormone_deficiency' as disease_alias, * from cohorts__rare_isolated_growth_hormone_deficiency
 UNION select distinct 'beckwith_wiedemann_syndrome' as disease_alias, * from cohorts__rare_beckwith_wiedemann_syndrome
 UNION select distinct 'prader_willi_syndrome' as disease_alias, * from cohorts__rare_prader_willi_syndrome
 UNION select distinct 'russell_silver_syndrome' as disease_alias, * from cohorts__rare_russell_silver_syndrome
 UNION select distinct 'congenital_hyperinsulinism' as disease_alias, * from cohorts__rare_congenital_hyperinsulinism
 UNION select distinct 'hirschsprung_disease' as disease_alias, * from cohorts__rare_hirschsprung_disease
 UNION select distinct 'biliary_atresia' as disease_alias, * from cohorts__rare_biliary_atresia
 UNION select distinct 'alagille_syndrome' as disease_alias, * from cohorts__rare_alagille_syndrome
 UNION select distinct 'shwachman_diamond_syndrome' as disease_alias, * from cohorts__rare_shwachman_diamond_syndrome
 UNION select distinct 'alpha_1_antitrypsin_deficiency' as disease_alias, * from cohorts__rare_alpha_1_antitrypsin_deficiency
 UNION select distinct 'chronic_intestinal_pseudo_obstruction' as disease_alias, * from cohorts__rare_chronic_intestinal_pseudo_obstruction
 UNION select distinct 'fanconi_anemia' as disease_alias, * from cohorts__rare_fanconi_anemia
 UNION select distinct 'diamond_blackfan_anemia' as disease_alias, * from cohorts__rare_diamond_blackfan_anemia
 UNION select distinct 'hemophilia_a' as disease_alias, * from cohorts__rare_hemophilia_a
 UNION select distinct 'beta_thalassemia_major' as disease_alias, * from cohorts__rare_beta_thalassemia_major
 UNION select distinct 'chronic_granulomatous_disease' as disease_alias, * from cohorts__rare_chronic_granulomatous_disease
 UNION select distinct 'wiskott_aldrich_syndrome' as disease_alias, * from cohorts__rare_wiskott_aldrich_syndrome
 UNION select distinct 'x_linked_agammaglobulinemia' as disease_alias, * from cohorts__rare_x_linked_agammaglobulinemia
 UNION select distinct 'familial_hemophagocytic_lymphohistiocytosis' as disease_alias, * from cohorts__rare_familial_hemophagocytic_lymphohistiocytosis
 UNION select distinct 'severe_combined_immunodeficiency' as disease_alias, * from cohorts__rare_severe_combined_immunodeficiency
 UNION select distinct 'charge_syndrome' as disease_alias, * from cohorts__rare_charge_syndrome
 UNION select distinct 'vacterl_vater_association' as disease_alias, * from cohorts__rare_vacterl_vater_association
 UNION select distinct 'bardet_biedl_syndrome' as disease_alias, * from cohorts__rare_bardet_biedl_syndrome
 UNION select distinct 'stickler_syndrome' as disease_alias, * from cohorts__rare_stickler_syndrome
 UNION select distinct 'sensenbrenner_syndrome' as disease_alias, * from cohorts__rare_sensenbrenner_syndrome
 UNION select distinct 'pseudoachondroplasia' as disease_alias, * from cohorts__rare_pseudoachondroplasia
 UNION select distinct 'osteogenesis_imperfecta' as disease_alias, * from cohorts__rare_osteogenesis_imperfecta
 UNION select distinct 'ehlers_danlos_syndrome' as disease_alias, * from cohorts__rare_ehlers_danlos_syndrome
 UNION select distinct 'ullrich_congenital_muscular_dystrophy' as disease_alias, * from cohorts__rare_ullrich_congenital_muscular_dystrophy
 UNION select distinct 'cleidocranial_dysplasia' as disease_alias, * from cohorts__rare_cleidocranial_dysplasia
 UNION select distinct 'pompe_disease' as disease_alias, * from cohorts__rare_pompe_disease
 UNION select distinct 'pitt_hopkins_syndrome' as disease_alias, * from cohorts__rare_pitt_hopkins_syndrome
 UNION select distinct 'rett_syndrome' as disease_alias, * from cohorts__rare_rett_syndrome
 UNION select distinct 'angelman_syndrome' as disease_alias, * from cohorts__rare_angelman_syndrome
 UNION select distinct 'dravet_syndrome' as disease_alias, * from cohorts__rare_dravet_syndrome
 UNION select distinct 'lennox_gastaut_syndrome' as disease_alias, * from cohorts__rare_lennox_gastaut_syndrome
 UNION select distinct 'juvenile_myoclonic_epilepsy' as disease_alias, * from cohorts__rare_juvenile_myoclonic_epilepsy
 UNION select distinct '1p36_deletion_syndrome' as disease_alias, * from cohorts__rare_1p36_deletion_syndrome
 UNION select distinct '16p11_2_microdeletion_syndrome' as disease_alias, * from cohorts__rare_16p11_2_microdeletion_syndrome
 UNION select distinct 'kabuki_syndrome' as disease_alias, * from cohorts__rare_kabuki_syndrome
 UNION select distinct 'tuberous_sclerosis_complex' as disease_alias, * from cohorts__rare_tuberous_sclerosis_complex
 UNION select distinct 'neurofibromatosis_type_1' as disease_alias, * from cohorts__rare_neurofibromatosis_type_1
 UNION select distinct 'friedreich_ataxia' as disease_alias, * from cohorts__rare_friedreich_ataxia
 UNION select distinct 'ataxia_telangiectasia' as disease_alias, * from cohorts__rare_ataxia_telangiectasia
 UNION select distinct 'spinal_muscular_atrophy' as disease_alias, * from cohorts__rare_spinal_muscular_atrophy
 UNION select distinct 'duchenne_muscular_dystrophy' as disease_alias, * from cohorts__rare_duchenne_muscular_dystrophy
 UNION select distinct 'sturge_weber_syndrome' as disease_alias, * from cohorts__rare_sturge_weber_syndrome
 UNION select distinct 'hereditary_neuropathy_with_liability_to_pressure_palsies' as disease_alias, * from cohorts__rare_hereditary_neuropathy_with_liability_to_pressure_palsies
 UNION select distinct 'aicardi_syndrome' as disease_alias, * from cohorts__rare_aicardi_syndrome
 UNION select distinct 'neuronal_ceroid_lipofuscinosis' as disease_alias, * from cohorts__rare_neuronal_ceroid_lipofuscinosis
 UNION select distinct 'fragile_x_syndrome' as disease_alias, * from cohorts__rare_fragile_x_syndrome
 UNION select distinct 'joubert_syndrome' as disease_alias, * from cohorts__rare_joubert_syndrome
 UNION select distinct 'x_linked_adrenoleukodystrophy' as disease_alias, * from cohorts__rare_x_linked_adrenoleukodystrophy
 UNION select distinct 'prader_willi_syndrome' as disease_alias, * from cohorts__rare_prader_willi_syndrome
 UNION select distinct 'cog8_congenital_disorders_of_glycosylation' as disease_alias, * from cohorts__rare_cog8_congenital_disorders_of_glycosylation
 UNION select distinct 'transaldolase_deficiency' as disease_alias, * from cohorts__rare_transaldolase_deficiency
 UNION select distinct 'stargardt_disease' as disease_alias, * from cohorts__rare_stargardt_disease
 UNION select distinct 'usher_syndrome' as disease_alias, * from cohorts__rare_usher_syndrome
 UNION select distinct 'leber_congenital_amaurosis' as disease_alias, * from cohorts__rare_leber_congenital_amaurosis
 UNION select distinct 'achromatopsia' as disease_alias, * from cohorts__rare_achromatopsia
 UNION select distinct 'primary_ciliary_dyskinesia' as disease_alias, * from cohorts__rare_primary_ciliary_dyskinesia
 UNION select distinct 'cystic_fibrosis' as disease_alias, * from cohorts__rare_cystic_fibrosis
 UNION select distinct 'pediatric_bronchiectasis' as disease_alias, * from cohorts__rare_pediatric_bronchiectasis
 UNION select distinct 'childhood_interstitial_lung_disease' as disease_alias, * from cohorts__rare_childhood_interstitial_lung_disease
 UNION select distinct 'pediatric_pulmonary_hypertension' as disease_alias, * from cohorts__rare_pediatric_pulmonary_hypertension
 UNION select distinct 'surfactant_protein_deficiencies' as disease_alias, * from cohorts__rare_surfactant_protein_deficiencies
 UNION select distinct 'alport_syndrome' as disease_alias, * from cohorts__rare_alport_syndrome
 UNION select distinct 'autosomal_recessive_polycystic_kidney_disease' as disease_alias, * from cohorts__rare_autosomal_recessive_polycystic_kidney_disease
 UNION select distinct 'nephronophthisis' as disease_alias, * from cohorts__rare_nephronophthisis
 UNION select distinct 'gitelman_syndrome' as disease_alias, * from cohorts__rare_gitelman_syndrome
 UNION select distinct 'cystinuria' as disease_alias, * from cohorts__rare_cystinuria
 UNION select distinct 'systemic_onset_juvenile_idiopathic_arthritis' as disease_alias, * from cohorts__rare_systemic_onset_juvenile_idiopathic_arthritis
 UNION select distinct 'opsoclonus_myoclonus_syndrome' as disease_alias, * from cohorts__rare_opsoclonus_myoclonus_syndrome
 UNION select distinct 'neurodegeneration_spasticity_cerebellar_atrophy_cortical_visual_impairment_syndrome' as disease_alias, * from cohorts__rare_neurodegeneration_spasticity_cerebellar_atrophy_cortical_visual_impairment_syndrome
 UNION select distinct 'hereditary_hemorrhagic_telangiectasia' as disease_alias, * from cohorts__rare_hereditary_hemorrhagic_telangiectasia
 UNION select distinct 'loeys_dietz_syndrome' as disease_alias, * from cohorts__rare_loeys_dietz_syndrome
 UNION select distinct 'pseudohypoparathyroidism_type_1a' as disease_alias, * from cohorts__rare_pseudohypoparathyroidism_type_1a
 UNION select distinct 'mccune_albright_syndrome' as disease_alias, * from cohorts__rare_mccune_albright_syndrome
 UNION select distinct 'flna_related_x_linked_myxomatous_valvular_dysplasia' as disease_alias, * from cohorts__rare_flna_related_x_linked_myxomatous_valvular_dysplasia
 UNION select distinct 'melnick_needles_osteodysplasty' as disease_alias, * from cohorts__rare_melnick_needles_osteodysplasty
 UNION select distinct 'otopalataldigital_syndrome_type_1' as disease_alias, * from cohorts__rare_otopalataldigital_syndrome_type_1
 UNION select distinct 'otopalataldigital_syndrome_type_2' as disease_alias, * from cohorts__rare_otopalataldigital_syndrome_type_2
 UNION select distinct 'bannayan_riley_ruvalcaba_syndrome' as disease_alias, * from cohorts__rare_bannayan_riley_ruvalcaba_syndrome
 UNION select distinct 'cowden_syndrome_multiple_hamartoma_syndrome' as disease_alias, * from cohorts__rare_cowden_syndrome_multiple_hamartoma_syndrome
 UNION select distinct 'steinert_myotonic_dystrophy' as disease_alias, * from cohorts__rare_steinert_myotonic_dystrophy
 UNION select distinct 'smith_magenis_syndrome' as disease_alias, * from cohorts__rare_smith_magenis_syndrome
 UNION select distinct 'barth_syndrome' as disease_alias, * from cohorts__rare_barth_syndrome
 UNION select distinct 'alport_syndrome' as disease_alias, * from cohorts__rare_alport_syndrome
 UNION select distinct 'rubinstein_taybi_syndrome' as disease_alias, * from cohorts__rare_rubinstein_taybi_syndrome