create or replace view cohorts__rare_codeset_broad_lt10_per_100k as select * from (values
('Hurler Syndrome', 'ORPHA:93412', 'E76.0', 'hurler_syndrome')
,('Hurler Syndrome', 'ORPHA:93412', 'E76.01', 'hurler_syndrome')
,('Hunter Syndrome', 'ORPHA:578', 'E76.1', 'hunter_syndrome')
,('Sanfilippo Syndrome', 'ORPHA:581', 'E76.2', 'sanfilippo_syndrome')
,('Morquio A Syndrome', 'ORPHA:585', 'E76.21', 'morquio_a_syndrome')
,('Krabbe Disease', 'ORPHA:762', 'E75.23', 'krabbe_disease')
,('Metachromatic Leukodystrophy', 'ORPHA:309', 'E75.25', 'metachromatic_leukodystrophy')
,('Niemann-Pick Disease Type C', 'ORPHA:646', 'E75.244', 'niemann_pick_disease_type_c')
,('Gaucher Disease', 'ORPHA:355', 'E75.22', 'gaucher_disease')
,('Pompe Disease', 'ORPHA:269', 'E74.09', 'pompe_disease')
,('Alpha-Mannosidosis', 'ORPHA:34', 'E77.0', 'alpha_mannosidosis')
,('Methylmalonic Acidemia', 'ORPHA:330', 'E71.12', 'methylmalonic_acidemia')
,('Propionic Acidemia', 'ORPHA:658', 'E71.121', 'propionic_acidemia')
,('Isovaleric Acidemia', 'ORPHA:211', 'E71.110', 'isovaleric_acidemia')
,('X-Linked Adrenoleukodystrophy', 'ORPHA:803', 'E71.52', 'x_linked_adrenoleukodystrophy')
,('Tay-Sachs Disease', 'ORPHA:580', 'E75.02', 'tay_sachs_disease')
,('Sandhoff Disease', 'ORPHA:3097', 'E75.03', 'sandhoff_disease')
,('Canavan Disease', 'ORPHA:33', 'E75.21', 'canavan_disease')
,('Alexander Disease', 'ORPHA:62', 'G37.8', 'alexander_disease')
,('Menkes Disease', 'ORPHA:972', 'E83.03', 'menkes_disease')
,('Crigler-Najjar Syndrome Type I', 'ORPHA:163', 'E80.6', 'crigler_najjar_syndrome_type_i')
,('Carbamoyl Phosphate Synthetase I Deficiency', 'ORPHA:31', 'E72.2', 'carbamoyl_phosphate_synthetase_i_deficiency')
,('Spinal Muscular Atrophy Type I', 'ORPHA:70', 'G12.0', 'spinal_muscular_atrophy_type_i')
,('Dystrophic Epidermolysis Bullosa', 'ORPHA:793', 'Q81.2', 'dystrophic_epidermolysis_bullosa')
,('MLASA', 'ORPHA:137969', 'D46.1', 'mlasa')
,('MLASA', 'ORPHA:137969', 'G71.3', 'mlasa')
,('2Q37 Deletion Syndrome', 'ORPHA:2617', 'Q93.5', '2q37_deletion_syndrome')
,('Wolf-Hirschhorn Syndrome', 'ORPHA:280', 'Q93.4', 'wolf_hirschhorn_syndrome')
,('Wolf-Hirschhorn Syndrome', 'ORPHA:280', 'Q93.5', 'wolf_hirschhorn_syndrome')
,('Mowat-Wilson Syndrome', 'ORPHA:2802', 'Q93.5', 'mowat_wilson_syndrome')
,('Smith-Magenis Syndrome', 'ORPHA:819', 'Q93.5', 'smith_magenis_syndrome')
,('Angelman Syndrome', 'ORPHA:913', 'Q93.5', 'angelman_syndrome')
,('Prader-Willi Syndrome', 'ORPHA:739', 'Q87.1', 'prader_willi_syndrome')
,('Kabuki Syndrome', 'ORPHA:628', 'Q87.89', 'kabuki_syndrome')
,('Coffin-Lowry Syndrome', 'ORPHA:215', 'Q90.9', 'coffin_lowry_syndrome')
,('Coffin-Lowry Syndrome', 'ORPHA:215', 'Q99', 'coffin_lowry_syndrome')
,('Aicardi Syndrome', 'ORPHA:34', 'Q04.0', 'aicardi_syndrome')
,('Aicardi Syndrome', 'ORPHA:34', 'H35.89', 'aicardi_syndrome')
,('Rubinstein-Taybi Syndrome', 'ORPHA:2780', 'Q87.89', 'rubinstein_taybi_syndrome')
,('Hallermann-Streiff Syndrome', 'ORPHA:2311', 'Q87.0', 'hallermann_streiff_syndrome')
,('Jacobsen Syndrome', 'ORPHA:1520', 'Q93.5', 'jacobsen_syndrome')
,('Miller-Dieker Syndrome', 'ORPHA:2501', 'Q04.3', 'miller_dieker_syndrome')
,('Miller-Dieker Syndrome', 'ORPHA:2501', 'Q93.5', 'miller_dieker_syndrome')
,('Shwachman-Diamond Syndrome', 'ORPHA:93', 'D61.1', 'shwachman_diamond_syndrome')
,('Shwachman-Diamond Syndrome', 'ORPHA:93', 'E84.19', 'shwachman_diamond_syndrome')
,('Leigh Syndrome', 'ORPHA:708', 'G31.81', 'leigh_syndrome')
,('Salla Disease', 'ORPHA:79405', 'E77.0', 'salla_disease')
,('Beckwith-Wiedemann Syndrome', 'ORPHA:116', 'Q87.3', 'beckwith_wiedemann_syndrome')
,('Cornelia De Lange Syndrome', 'ORPHA:2780', 'Q87.1', 'cornelia_de_lange_syndrome')
,('Medium-Chain Acyl-Coa Dehydrogenase Deficiency', 'ORPHA:42', 'E71.3', 'medium_chain_acyl_coa_dehydrogenase_deficiency')
,('Noonan Syndrome', 'ORPHA:648', 'Q87.1', 'noonan_syndrome')
) AS t (disease_name, orpha_code, icd10_code, disease_alias) ;