create or replace view cohorts__rare_codeset_unique_lt10_per_100k as select * from (values
('Hurler Syndrome', 'ORPHA:93412', 'E76.01', 'hurler_syndrome')
,('Hunter Syndrome', 'ORPHA:578', 'E76.1', 'hunter_syndrome')
,('Sanfilippo Syndrome', 'ORPHA:583', 'E76.2', 'sanfilippo_syndrome')
,('Morquio A Syndrome', 'ORPHA:585', 'E76.21', 'morquio_a_syndrome')
,('Krabbe Disease', 'ORPHA:762', 'E75.23', 'krabbe_disease')
,('Metachromatic Leukodystrophy', 'ORPHA:309', 'E75.25', 'metachromatic_leukodystrophy')
,('X-Linked Adrenoleukodystrophy', 'ORPHA:803', 'E71.52', 'x_linked_adrenoleukodystrophy')
,('Tay-Sachs Disease', 'ORPHA:580', 'E75.02', 'tay_sachs_disease')
,('Sandhoff Disease', 'ORPHA:3097', 'E75.03', 'sandhoff_disease')
,('Niemann-Pick Disease Type C', 'ORPHA:646', 'E75.244', 'niemann_pick_disease_type_c')
,('GSD Type Ia', 'ORPHA:358', 'E74.01', 'gsd_type_ia')
,('Homocystinuria', 'ORPHA:44', 'E72.11', 'homocystinuria')
,('Propionic Acidemia', 'ORPHA:658', 'E71.121', 'propionic_acidemia')
,('Methylmalonic Acidemia', 'ORPHA:330', 'E71.12', 'methylmalonic_acidemia')
,('Isovaleric Acidemia', 'ORPHA:211', 'E71.110', 'isovaleric_acidemia')
,('VLCAD Deficiency', 'ORPHA:215', 'E71.310', 'vlcad_deficiency')
,('Biotinidase Deficiency', 'ORPHA:351', 'E53.8', 'biotinidase_deficiency')
,('Pyruvate Dehydrogenase Complex Deficiency', 'ORPHA:703', 'E74.8', 'pyruvate_dehydrogenase_complex_deficiency')
,('Spinal Muscular Atrophy Type I', 'ORPHA:70', 'G12.0', 'spinal_muscular_atrophy_type_i')
,('Dystrophic Epidermolysis Bullosa', 'ORPHA:793', 'Q81.2', 'dystrophic_epidermolysis_bullosa')
) AS t (disease_name, orpha_code, icd10_code, disease_alias) ;