create or replace view cohorts__rare_codeset_broad_lt50_per_100k as select * from (values
('Noonan Syndrome', 'ORPHA:648', 'Q87.1', 'noonan_syndrome')
,('CHARGE Syndrome', 'ORPHA:138', 'Q87.8', 'charge_syndrome')
,('Pierre Robin Sequence', 'ORPHA:718', 'Q87.0', 'pierre_robin_sequence')
,('Goldenhar Syndrome', 'ORPHA:141132', 'Q87.0', 'goldenhar_syndrome')
,('Primary Ciliary Dyskinesia', 'ORPHA:244', 'J98.8', 'primary_ciliary_dyskinesia')
,('Primary Ciliary Dyskinesia', 'ORPHA:244', 'Q89.3', 'primary_ciliary_dyskinesia')
,('Stargardt Disease', 'ORPHA:827', 'H35.5', 'stargardt_disease')
,('Usher Syndrome', 'ORPHA:886', 'H35.5', 'usher_syndrome')
,('Usher Syndrome', 'ORPHA:886', 'H90.5', 'usher_syndrome')
,('Stickler Syndrome', 'ORPHA:828', 'Q87.0', 'stickler_syndrome')
,('1P36 Deletion Syndrome', 'ORPHA:1606', 'Q93.5', '1p36_deletion_syndrome')
,('16P11.2 Microdeletion Syndrome', 'ORPHA:261197', 'Q93.5', '16p11_2_microdeletion_syndrome')
,('Heterotaxy Syndrome', 'ORPHA:1572', 'Q89.3', 'heterotaxy_syndrome')
,('Medium-Chain Acyl-Coa Dehydrogenase Deficiency', 'ORPHA:42', 'E71.3', 'medium_chain_acyl_coa_dehydrogenase_deficiency')
,('VACTERL/VATER Association', 'ORPHA:90272', 'Q76', 'vacterl_vater_association')
,('VACTERL/VATER Association', 'ORPHA:90272', 'Q42', 'vacterl_vater_association')
,('Lennox-Gastaut Syndrome', 'ORPHA:646', 'G40.804', 'lennox_gastaut_syndrome')
,('Hereditary Neuropathy With Liability To Pressure Palsies', 'ORPHA:99957', 'G60.8', 'hereditary_neuropathy_with_liability_to_pressure_palsies')
,('Juvenile Myoclonic Epilepsy', 'ORPHA:2820', 'G40.3', 'juvenile_myoclonic_epilepsy')
,('Alport Syndrome', 'ORPHA:47', 'N07.8', 'alport_syndrome')
,('Isolated Growth Hormone Deficiency Type II', 'ORPHA:79219', 'E23.0', 'isolated_growth_hormone_deficiency_type_ii')
,('Spinocerebellar Ataxia Type 2', 'ORPHA:98753', 'G11.1', 'spinocerebellar_ataxia_type_2')
,('Refsum Disease', 'ORPHA:226', 'E71.52', 'refsum_disease')
,('Ullrich Congenital Muscular Dystrophy', 'ORPHA:58455', 'G71.0', 'ullrich_congenital_muscular_dystrophy')
,('Salla Disease', 'ORPHA:79405', 'E77.0', 'salla_disease')
,('Carbamoyl Phosphate Synthetase I Deficiency', 'ORPHA:31', 'E72.2', 'carbamoyl_phosphate_synthetase_i_deficiency')
,('Glutaric Aciduria Type 1', 'ORPHA:221', 'E71.121', 'glutaric_aciduria_type_1')
,('Sensenbrenner Syndrome', 'ORPHA:933', 'Q78.8', 'sensenbrenner_syndrome')
,('Beckwith-Wiedemann Syndrome', 'ORPHA:116', 'Q87.3', 'beckwith_wiedemann_syndrome')
,('Pseudoachondroplasia', 'ORPHA:91356', 'Q77.1', 'pseudoachondroplasia')
) AS t (disease_name, orpha_code, icd10_code, disease_alias) ;