create TABLE cohorts__rare_match_notes AS 
select distinct 'hurler_syndrome' as disease_alias, * from cohorts__rare_hurler_syndrome
 UNION select distinct 'hunter_syndrome' as disease_alias, * from cohorts__rare_hunter_syndrome
 UNION select distinct 'sanfilippo_syndrome' as disease_alias, * from cohorts__rare_sanfilippo_syndrome
 UNION select distinct 'morquio_a_syndrome' as disease_alias, * from cohorts__rare_morquio_a_syndrome
 UNION select distinct 'krabbe_disease' as disease_alias, * from cohorts__rare_krabbe_disease
 UNION select distinct 'metachromatic_leukodystrophy' as disease_alias, * from cohorts__rare_metachromatic_leukodystrophy
 UNION select distinct 'x_linked_adrenoleukodystrophy' as disease_alias, * from cohorts__rare_x_linked_adrenoleukodystrophy
 UNION select distinct 'tay_sachs_disease' as disease_alias, * from cohorts__rare_tay_sachs_disease
 UNION select distinct 'sandhoff_disease' as disease_alias, * from cohorts__rare_sandhoff_disease
 UNION select distinct 'niemann_pick_disease_type_c' as disease_alias, * from cohorts__rare_niemann_pick_disease_type_c
 UNION select distinct 'gsd_type_ia' as disease_alias, * from cohorts__rare_gsd_type_ia
 UNION select distinct 'homocystinuria' as disease_alias, * from cohorts__rare_homocystinuria
 UNION select distinct 'propionic_acidemia' as disease_alias, * from cohorts__rare_propionic_acidemia
 UNION select distinct 'methylmalonic_acidemia' as disease_alias, * from cohorts__rare_methylmalonic_acidemia
 UNION select distinct 'isovaleric_acidemia' as disease_alias, * from cohorts__rare_isovaleric_acidemia
 UNION select distinct 'vlcad_deficiency' as disease_alias, * from cohorts__rare_vlcad_deficiency
 UNION select distinct 'biotinidase_deficiency' as disease_alias, * from cohorts__rare_biotinidase_deficiency
 UNION select distinct 'pyruvate_dehydrogenase_complex_deficiency' as disease_alias, * from cohorts__rare_pyruvate_dehydrogenase_complex_deficiency
 UNION select distinct 'spinal_muscular_atrophy_type_i' as disease_alias, * from cohorts__rare_spinal_muscular_atrophy_type_i
 UNION select distinct 'dystrophic_epidermolysis_bullosa' as disease_alias, * from cohorts__rare_dystrophic_epidermolysis_bullosa
 UNION select distinct '22q11_2_deletion_syndrome' as disease_alias, * from cohorts__rare_22q11_2_deletion_syndrome
 UNION select distinct 'alpha_1_antitrypsin_deficiency' as disease_alias, * from cohorts__rare_alpha_1_antitrypsin_deficiency
 UNION select distinct 'angelman_syndrome' as disease_alias, * from cohorts__rare_angelman_syndrome
 UNION select distinct 'autosomal_recessive_polycystic_kidney_disease' as disease_alias, * from cohorts__rare_autosomal_recessive_polycystic_kidney_disease
 UNION select distinct 'beckwith_wiedemann_syndrome' as disease_alias, * from cohorts__rare_beckwith_wiedemann_syndrome
 UNION select distinct 'charcot_marie_tooth_disease' as disease_alias, * from cohorts__rare_charcot_marie_tooth_disease
 UNION select distinct 'charge_syndrome' as disease_alias, * from cohorts__rare_charge_syndrome
 UNION select distinct 'coarctation_of_aorta' as disease_alias, * from cohorts__rare_coarctation_of_aorta
 UNION select distinct 'congenital_adrenal_hyperplasia' as disease_alias, * from cohorts__rare_congenital_adrenal_hyperplasia
 UNION select distinct 'congenital_diaphragmatic_hernia' as disease_alias, * from cohorts__rare_congenital_diaphragmatic_hernia
 UNION select distinct 'congenital_hydrocephalus' as disease_alias, * from cohorts__rare_congenital_hydrocephalus
 UNION select distinct 'congenital_hypothyroidism' as disease_alias, * from cohorts__rare_congenital_hypothyroidism
 UNION select distinct 'congenital_long_qt_syndrome' as disease_alias, * from cohorts__rare_congenital_long_qt_syndrome
 UNION select distinct 'cystic_fibrosis' as disease_alias, * from cohorts__rare_cystic_fibrosis
 UNION select distinct 'duane_syndrome' as disease_alias, * from cohorts__rare_duane_syndrome
 UNION select distinct 'ehlers_danlos_syndrome' as disease_alias, * from cohorts__rare_ehlers_danlos_syndrome
 UNION select distinct 'erythropoietic_protoporphyria' as disease_alias, * from cohorts__rare_erythropoietic_protoporphyria
 UNION select distinct 'esophageal_atresia_tracheoesophageal_fistula' as disease_alias, * from cohorts__rare_esophageal_atresia_tracheoesophageal_fistula
 UNION select distinct 'fragile_x_syndrome' as disease_alias, * from cohorts__rare_fragile_x_syndrome
 UNION select distinct 'gastroschisis' as disease_alias, * from cohorts__rare_gastroschisis
 UNION select distinct 'hemophilia_a' as disease_alias, * from cohorts__rare_hemophilia_a
 UNION select distinct 'hereditary_spherocytosis' as disease_alias, * from cohorts__rare_hereditary_spherocytosis
 UNION select distinct 'hirschsprung_disease' as disease_alias, * from cohorts__rare_hirschsprung_disease
 UNION select distinct 'hypoplastic_left_heart_syndrome' as disease_alias, * from cohorts__rare_hypoplastic_left_heart_syndrome
 UNION select distinct 'imperforate_anus' as disease_alias, * from cohorts__rare_imperforate_anus
 UNION select distinct 'juvenile_idiopathic_arthritis' as disease_alias, * from cohorts__rare_juvenile_idiopathic_arthritis
 UNION select distinct 'marfan_syndrome' as disease_alias, * from cohorts__rare_marfan_syndrome
 UNION select distinct 'maple_syrup_urine_disease' as disease_alias, * from cohorts__rare_maple_syrup_urine_disease
 UNION select distinct 'medium_chain_acyl_coa_dehydrogenase_deficiency' as disease_alias, * from cohorts__rare_medium_chain_acyl_coa_dehydrogenase_deficiency
 UNION select distinct 'melas_syndrome' as disease_alias, * from cohorts__rare_melas_syndrome
 UNION select distinct 'microtia' as disease_alias, * from cohorts__rare_microtia
 UNION select distinct 'neurofibromatosis_type_1' as disease_alias, * from cohorts__rare_neurofibromatosis_type_1
 UNION select distinct 'noonan_syndrome' as disease_alias, * from cohorts__rare_noonan_syndrome
 UNION select distinct 'omphalocele' as disease_alias, * from cohorts__rare_omphalocele
 UNION select distinct 'phenylketonuria' as disease_alias, * from cohorts__rare_phenylketonuria
 UNION select distinct 'posterior_urethral_valves' as disease_alias, * from cohorts__rare_posterior_urethral_valves
 UNION select distinct 'prader_willi_syndrome' as disease_alias, * from cohorts__rare_prader_willi_syndrome
 UNION select distinct 'primary_congenital_glaucoma' as disease_alias, * from cohorts__rare_primary_congenital_glaucoma
 UNION select distinct 'rett_syndrome' as disease_alias, * from cohorts__rare_rett_syndrome
 UNION select distinct 'sickle_cell_disease' as disease_alias, * from cohorts__rare_sickle_cell_disease
 UNION select distinct 'small_intestinal_atresia' as disease_alias, * from cohorts__rare_small_intestinal_atresia
 UNION select distinct 'spina_bifida' as disease_alias, * from cohorts__rare_spina_bifida
 UNION select distinct 'stargardt_disease' as disease_alias, * from cohorts__rare_stargardt_disease
 UNION select distinct 'stickler_syndrome' as disease_alias, * from cohorts__rare_stickler_syndrome
 UNION select distinct 'tetralogy_of_fallot' as disease_alias, * from cohorts__rare_tetralogy_of_fallot
 UNION select distinct 'transposition_of_the_great_arteries' as disease_alias, * from cohorts__rare_transposition_of_the_great_arteries
 UNION select distinct 'tuberous_sclerosis_complex' as disease_alias, * from cohorts__rare_tuberous_sclerosis_complex
 UNION select distinct 'turner_syndrome' as disease_alias, * from cohorts__rare_turner_syndrome
 UNION select distinct 'williams_syndrome' as disease_alias, * from cohorts__rare_williams_syndrome
 UNION select distinct 'hurler_syndrome' as disease_alias, * from cohorts__rare_hurler_syndrome
 UNION select distinct 'hunter_syndrome' as disease_alias, * from cohorts__rare_hunter_syndrome
 UNION select distinct 'sanfilippo_syndrome' as disease_alias, * from cohorts__rare_sanfilippo_syndrome
 UNION select distinct 'morquio_a_syndrome' as disease_alias, * from cohorts__rare_morquio_a_syndrome
 UNION select distinct 'krabbe_disease' as disease_alias, * from cohorts__rare_krabbe_disease
 UNION select distinct 'metachromatic_leukodystrophy' as disease_alias, * from cohorts__rare_metachromatic_leukodystrophy
 UNION select distinct 'niemann_pick_disease_type_c' as disease_alias, * from cohorts__rare_niemann_pick_disease_type_c
 UNION select distinct 'gaucher_disease' as disease_alias, * from cohorts__rare_gaucher_disease
 UNION select distinct 'pompe_disease' as disease_alias, * from cohorts__rare_pompe_disease
 UNION select distinct 'alpha_mannosidosis' as disease_alias, * from cohorts__rare_alpha_mannosidosis
 UNION select distinct 'methylmalonic_acidemia' as disease_alias, * from cohorts__rare_methylmalonic_acidemia
 UNION select distinct 'propionic_acidemia' as disease_alias, * from cohorts__rare_propionic_acidemia
 UNION select distinct 'isovaleric_acidemia' as disease_alias, * from cohorts__rare_isovaleric_acidemia
 UNION select distinct 'x_linked_adrenoleukodystrophy' as disease_alias, * from cohorts__rare_x_linked_adrenoleukodystrophy
 UNION select distinct 'tay_sachs_disease' as disease_alias, * from cohorts__rare_tay_sachs_disease
 UNION select distinct 'sandhoff_disease' as disease_alias, * from cohorts__rare_sandhoff_disease
 UNION select distinct 'canavan_disease' as disease_alias, * from cohorts__rare_canavan_disease
 UNION select distinct 'alexander_disease' as disease_alias, * from cohorts__rare_alexander_disease
 UNION select distinct 'menkes_disease' as disease_alias, * from cohorts__rare_menkes_disease
 UNION select distinct 'crigler_najjar_syndrome_type_i' as disease_alias, * from cohorts__rare_crigler_najjar_syndrome_type_i
 UNION select distinct 'carbamoyl_phosphate_synthetase_i_deficiency' as disease_alias, * from cohorts__rare_carbamoyl_phosphate_synthetase_i_deficiency
 UNION select distinct 'spinal_muscular_atrophy_type_i' as disease_alias, * from cohorts__rare_spinal_muscular_atrophy_type_i
 UNION select distinct 'dystrophic_epidermolysis_bullosa' as disease_alias, * from cohorts__rare_dystrophic_epidermolysis_bullosa
 UNION select distinct 'mlasa' as disease_alias, * from cohorts__rare_mlasa
 UNION select distinct '2q37_deletion_syndrome' as disease_alias, * from cohorts__rare_2q37_deletion_syndrome
 UNION select distinct 'wolf_hirschhorn_syndrome' as disease_alias, * from cohorts__rare_wolf_hirschhorn_syndrome
 UNION select distinct 'mowat_wilson_syndrome' as disease_alias, * from cohorts__rare_mowat_wilson_syndrome
 UNION select distinct 'smith_magenis_syndrome' as disease_alias, * from cohorts__rare_smith_magenis_syndrome
 UNION select distinct 'angelman_syndrome' as disease_alias, * from cohorts__rare_angelman_syndrome
 UNION select distinct 'prader_willi_syndrome' as disease_alias, * from cohorts__rare_prader_willi_syndrome
 UNION select distinct 'kabuki_syndrome' as disease_alias, * from cohorts__rare_kabuki_syndrome
 UNION select distinct 'coffin_lowry_syndrome' as disease_alias, * from cohorts__rare_coffin_lowry_syndrome
 UNION select distinct 'aicardi_syndrome' as disease_alias, * from cohorts__rare_aicardi_syndrome
 UNION select distinct 'rubinstein_taybi_syndrome' as disease_alias, * from cohorts__rare_rubinstein_taybi_syndrome
 UNION select distinct 'hallermann_streiff_syndrome' as disease_alias, * from cohorts__rare_hallermann_streiff_syndrome
 UNION select distinct 'jacobsen_syndrome' as disease_alias, * from cohorts__rare_jacobsen_syndrome
 UNION select distinct 'miller_dieker_syndrome' as disease_alias, * from cohorts__rare_miller_dieker_syndrome
 UNION select distinct 'shwachman_diamond_syndrome' as disease_alias, * from cohorts__rare_shwachman_diamond_syndrome
 UNION select distinct 'leigh_syndrome' as disease_alias, * from cohorts__rare_leigh_syndrome
 UNION select distinct 'salla_disease' as disease_alias, * from cohorts__rare_salla_disease
 UNION select distinct 'beckwith_wiedemann_syndrome' as disease_alias, * from cohorts__rare_beckwith_wiedemann_syndrome
 UNION select distinct 'cornelia_de_lange_syndrome' as disease_alias, * from cohorts__rare_cornelia_de_lange_syndrome
 UNION select distinct 'medium_chain_acyl_coa_dehydrogenase_deficiency' as disease_alias, * from cohorts__rare_medium_chain_acyl_coa_dehydrogenase_deficiency
 UNION select distinct 'noonan_syndrome' as disease_alias, * from cohorts__rare_noonan_syndrome
 UNION select distinct 'noonan_syndrome' as disease_alias, * from cohorts__rare_noonan_syndrome
 UNION select distinct 'charge_syndrome' as disease_alias, * from cohorts__rare_charge_syndrome
 UNION select distinct 'pierre_robin_sequence' as disease_alias, * from cohorts__rare_pierre_robin_sequence
 UNION select distinct 'goldenhar_syndrome' as disease_alias, * from cohorts__rare_goldenhar_syndrome
 UNION select distinct 'primary_ciliary_dyskinesia' as disease_alias, * from cohorts__rare_primary_ciliary_dyskinesia
 UNION select distinct 'stargardt_disease' as disease_alias, * from cohorts__rare_stargardt_disease
 UNION select distinct 'usher_syndrome' as disease_alias, * from cohorts__rare_usher_syndrome
 UNION select distinct 'stickler_syndrome' as disease_alias, * from cohorts__rare_stickler_syndrome
 UNION select distinct '1p36_deletion_syndrome' as disease_alias, * from cohorts__rare_1p36_deletion_syndrome
 UNION select distinct '16p11_2_microdeletion_syndrome' as disease_alias, * from cohorts__rare_16p11_2_microdeletion_syndrome
 UNION select distinct 'heterotaxy_syndrome' as disease_alias, * from cohorts__rare_heterotaxy_syndrome
 UNION select distinct 'medium_chain_acyl_coa_dehydrogenase_deficiency' as disease_alias, * from cohorts__rare_medium_chain_acyl_coa_dehydrogenase_deficiency
 UNION select distinct 'vacterl_vater_association' as disease_alias, * from cohorts__rare_vacterl_vater_association
 UNION select distinct 'lennox_gastaut_syndrome' as disease_alias, * from cohorts__rare_lennox_gastaut_syndrome
 UNION select distinct 'hereditary_neuropathy_with_liability_to_pressure_palsies' as disease_alias, * from cohorts__rare_hereditary_neuropathy_with_liability_to_pressure_palsies
 UNION select distinct 'juvenile_myoclonic_epilepsy' as disease_alias, * from cohorts__rare_juvenile_myoclonic_epilepsy
 UNION select distinct 'alport_syndrome' as disease_alias, * from cohorts__rare_alport_syndrome
 UNION select distinct 'isolated_growth_hormone_deficiency_type_ii' as disease_alias, * from cohorts__rare_isolated_growth_hormone_deficiency_type_ii
 UNION select distinct 'spinocerebellar_ataxia_type_2' as disease_alias, * from cohorts__rare_spinocerebellar_ataxia_type_2
 UNION select distinct 'refsum_disease' as disease_alias, * from cohorts__rare_refsum_disease
 UNION select distinct 'ullrich_congenital_muscular_dystrophy' as disease_alias, * from cohorts__rare_ullrich_congenital_muscular_dystrophy
 UNION select distinct 'salla_disease' as disease_alias, * from cohorts__rare_salla_disease
 UNION select distinct 'carbamoyl_phosphate_synthetase_i_deficiency' as disease_alias, * from cohorts__rare_carbamoyl_phosphate_synthetase_i_deficiency
 UNION select distinct 'glutaric_aciduria_type_1' as disease_alias, * from cohorts__rare_glutaric_aciduria_type_1
 UNION select distinct 'sensenbrenner_syndrome' as disease_alias, * from cohorts__rare_sensenbrenner_syndrome
 UNION select distinct 'beckwith_wiedemann_syndrome' as disease_alias, * from cohorts__rare_beckwith_wiedemann_syndrome
 UNION select distinct 'pseudoachondroplasia' as disease_alias, * from cohorts__rare_pseudoachondroplasia