create or replace view cohorts__rare_codeset_unique_lt50_per_100k as select * from (values
('22Q11.2 Deletion Syndrome', 'ORPHA:567', 'D82.1', '22q11_2_deletion_syndrome')
,('Alpha-1 Antitrypsin Deficiency', 'ORPHA:60', 'E88.01', 'alpha_1_antitrypsin_deficiency')
,('Angelman Syndrome', 'ORPHA:72', 'Q93.51', 'angelman_syndrome')
,('Autosomal Recessive Polycystic Kidney Disease', 'ORPHA:731', 'Q61.1', 'autosomal_recessive_polycystic_kidney_disease')
,('Beckwith-Wiedemann Syndrome', 'ORPHA:116', 'Q87.3', 'beckwith_wiedemann_syndrome')
,('Charcot-Marie-Tooth Disease', 'ORPHA:166', 'G60.0', 'charcot_marie_tooth_disease')
,('CHARGE Syndrome', 'ORPHA:138', 'Q87.8', 'charge_syndrome')
,('Coarctation Of Aorta', 'ORPHA:1457', 'Q25.1', 'coarctation_of_aorta')
,('Congenital Adrenal Hyperplasia', 'ORPHA:90794', 'E25.0', 'congenital_adrenal_hyperplasia')
,('Congenital Diaphragmatic Hernia', 'ORPHA:2140', 'Q79.0', 'congenital_diaphragmatic_hernia')
,('Congenital Hydrocephalus', 'ORPHA:2185', 'Q03', 'congenital_hydrocephalus')
,('Congenital Hypothyroidism', 'ORPHA:95711', 'E03.0', 'congenital_hypothyroidism')
,('Congenital Hypothyroidism', 'ORPHA:95711', 'E03.1', 'congenital_hypothyroidism')
,('Congenital Long QT Syndrome', 'ORPHA:768', 'I45.81', 'congenital_long_qt_syndrome')
,('Cystic Fibrosis', 'ORPHA:586', 'E84.0', 'cystic_fibrosis')
,('Cystic Fibrosis', 'ORPHA:586', 'E84.1', 'cystic_fibrosis')
,('Cystic Fibrosis', 'ORPHA:586', 'E84', 'cystic_fibrosis')
,('Duane Syndrome', 'ORPHA:233', 'H50.811', 'duane_syndrome')
,('Ehlers-Danlos Syndrome', 'ORPHA:287', 'Q79.6', 'ehlers_danlos_syndrome')
,('Erythropoietic Protoporphyria', 'ORPHA:79278', 'E80.0', 'erythropoietic_protoporphyria')
,('Esophageal Atresia Tracheoesophageal Fistula', 'ORPHA:1199', 'Q39.0', 'esophageal_atresia_tracheoesophageal_fistula')
,('Esophageal Atresia Tracheoesophageal Fistula', 'ORPHA:1199', 'Q39.4', 'esophageal_atresia_tracheoesophageal_fistula')
,('Fragile X Syndrome', 'ORPHA:908', 'Q99.2', 'fragile_x_syndrome')
,('Gastroschisis', 'ORPHA:2368', 'Q79.3', 'gastroschisis')
,('Hemophilia A', 'ORPHA:98878', 'D66', 'hemophilia_a')
,('Hereditary Spherocytosis', 'ORPHA:822', 'D58.0', 'hereditary_spherocytosis')
,('Hirschsprung Disease', 'ORPHA:388', 'Q43.1', 'hirschsprung_disease')
,('Hypoplastic Left Heart Syndrome', 'ORPHA:2248', 'Q23.4', 'hypoplastic_left_heart_syndrome')
,('Imperforate Anus', 'ORPHA:96346', 'Q42.2', 'imperforate_anus')
,('Imperforate Anus', 'ORPHA:96346', 'Q42.3', 'imperforate_anus')
,('Juvenile Idiopathic Arthritis', 'ORPHA:92', 'M08.0', 'juvenile_idiopathic_arthritis')
,('Juvenile Idiopathic Arthritis', 'ORPHA:92', 'M08.4', 'juvenile_idiopathic_arthritis')
,('Juvenile Idiopathic Arthritis', 'ORPHA:92', 'M08.8', 'juvenile_idiopathic_arthritis')
,('Marfan Syndrome', 'ORPHA:558', 'Q87.40', 'marfan_syndrome')
,('Marfan Syndrome', 'ORPHA:558', 'Q87.43', 'marfan_syndrome')
,('Maple Syrup Urine Disease', 'ORPHA:511', 'E71.0', 'maple_syrup_urine_disease')
,('Medium-Chain Acyl-Coa Dehydrogenase Deficiency', 'ORPHA:42', 'E71.312', 'medium_chain_acyl_coa_dehydrogenase_deficiency')
,('MELAS Syndrome', 'ORPHA:550', 'G31.82', 'melas_syndrome')
,('Microtia', 'ORPHA:83463', 'Q17.2', 'microtia')
,('Neurofibromatosis Type 1', 'ORPHA:636', 'Q85.01', 'neurofibromatosis_type_1')
,('Noonan Syndrome', 'ORPHA:648', 'Q87.1', 'noonan_syndrome')
,('Omphalocele', 'ORPHA:660', 'Q79.2', 'omphalocele')
,('Phenylketonuria', 'ORPHA:716', 'E70.0', 'phenylketonuria')
,('Posterior Urethral Valves', 'ORPHA:93110', 'Q64.2', 'posterior_urethral_valves')
,('Prader-Willi Syndrome', 'ORPHA:739', 'Q87.1', 'prader_willi_syndrome')
,('Primary Congenital Glaucoma', 'ORPHA:98976', 'Q15.0', 'primary_congenital_glaucoma')
,('Rett Syndrome', 'ORPHA:778', 'F84.2', 'rett_syndrome')
,('Sickle Cell Disease', 'ORPHA:232', 'D57.0', 'sickle_cell_disease')
,('Sickle Cell Disease', 'ORPHA:232', 'D57.1', 'sickle_cell_disease')
,('Small Intestinal Atresia', 'ORPHA:1201', 'Q41.0', 'small_intestinal_atresia')
,('Small Intestinal Atresia', 'ORPHA:1201', 'Q41.2', 'small_intestinal_atresia')
,('Spina Bifida', 'ORPHA:823', 'Q05', 'spina_bifida')
,('Stargardt Disease', 'ORPHA:827', 'H35.52', 'stargardt_disease')
,('Stickler Syndrome', 'ORPHA:828', 'Q87.8', 'stickler_syndrome')
,('Tetralogy Of Fallot', 'ORPHA:3303', 'Q21.3', 'tetralogy_of_fallot')
,('Transposition Of The Great Arteries', 'ORPHA:860', 'Q20.3', 'transposition_of_the_great_arteries')
,('Tuberous Sclerosis Complex', 'ORPHA:805', 'Q85.1', 'tuberous_sclerosis_complex')
,('Turner Syndrome', 'ORPHA:881', 'Q96.0', 'turner_syndrome')
,('Turner Syndrome', 'ORPHA:881', 'Q96.9', 'turner_syndrome')
,('Williams Syndrome', 'ORPHA:904', 'Q93.82', 'williams_syndrome')
) AS t (disease_name, orpha_code, icd10_code, disease_alias) ;